[package]
name = "cddl_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbor_event = "2.1.3"
cddl = "0.8.1"
codegen = "0.1.1"
either = "1.5.3"
